title: Open PHP Error Specifications
tagline: Standardize your error handling.
description: >
    This site outlines standards for handling PHP errors, and how to implement
    these standards within your own projects and libraries.
url: https://php-errors.github.io/
