title: An Open PHP Error Handler Specification
tagline: Standardize your error handling.
description: >
    This site outlines a standard for handling PHP errors, and how to implement
    this standard within your own projects and libraries.
url: https://php-errors.github.io/
